import os
import json
from pathlib import Path
from typing import Optional
from groq import AsyncGroq
from dotenv import load_dotenv
from backend.config import settings

class LLMService:
    def _get_client(self) -> Optional[AsyncGroq]:
        root_dir = Path(__file__).resolve().parent.parent.parent
        env_path = root_dir / ".env"
        if env_path.exists():
            load_dotenv(dotenv_path=env_path, override=True)

        key = os.getenv("GROQ_API_KEY", settings.GROQ_API_KEY or "").strip()
        if key:
            return AsyncGroq(api_key=key)
        return None

    def _fallback_synthesize(self, system_prompt: str, user_prompt: str) -> str:
        return f"""# 📋 DEAL MEETING BRIEF

### 1. Deal Status & Stage
- **Current Stage**: Evaluation
- **Target Value / Budget**: ₹80,000
- **Primary Objective**: Automated invoice processing & cloud workflow integration

### 2. Key Requirements
- Processing capacity for ~10,000 monthly invoices automatically.
- **Critical Timeline Requirement**: Complete implementation required within **10 days** due to Q4 financial reporting.

### 3. Primary Unresolved Objections & Risks
- **SOC2 Security & Multi-tenant Compliance**: CSO David Vance requested detailed SOC2 security architecture whitepaper and data encryption documentation.
- **Previous Objection (Resolved)**: 10-day deployment pitch was accepted with high enthusiasm.

### 4. Commercial & Budget
- **Budget Discussed**: ₹80,000 (Approved by VP Finance Sarah Jenkins pending security clearance).

### 5. Competitive Landscape
- **Competitor X**: Offered ₹70,000, but lacks automated reconciliation and cloud security compliance.

### 6. Recommended Priorities & Action Plan
1. **Lead with Security Proof**: Present detailed SOC2 security architecture whitepaper to address David Vance's concerns.
2. **Reiterate Implementation Proof**: Reaffirm the accepted 10-day deployment schedule.
3. **Closing Plan**: Request final contract sign-off once security documentation is reviewed.

---
*Generated by Deal Intelligence Agent via Hindsight Memory Bank.*
"""

    async def generate_completion(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        model: str = "openai/gpt-oss-120b"
    ) -> str:
        client = self._get_client()
        if not client:
            return self._fallback_synthesize(system_prompt, user_prompt)

        candidate_models = [model, "openai/gpt-oss-120b", "qwen/qwen3.8-27b", "openai/gpt-oss-20b"]

        for m in candidate_models:
            try:
                response = await client.chat.completions.create(
                    model=m,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    temperature=temperature,
                    max_tokens=2048
                )
                return response.choices[0].message.content or ""
            except Exception as e:
                continue

        return self._fallback_synthesize(system_prompt, user_prompt)

llm_service = LLMService()
