import json
import re
from typing import Optional, List, Dict, Any
from groq import AsyncGroq
from backend.config import settings

class LLMService:
    def __init__(self):
        self.api_key = settings.GROQ_API_KEY
        if self.api_key and self.api_key.strip():
            self.client = AsyncGroq(api_key=self.api_key.strip())
        else:
            self.client = None

    def _fallback_synthesize(self, system_prompt: str, user_prompt: str) -> str:
        """
        Smart fallback synthesis when Groq API key is not set.
        Extracts facts from prompt context and structures a clean Markdown brief.
        """
        # Try extracting memory context
        if "RETRIVED HINDSIGHT MEMORY CONTEXT:" in user_prompt:
            try:
                context_part = user_prompt.split("RETRIVED HINDSIGHT MEMORY CONTEXT:")[1].split("\n\nGenerate")[0]
            except Exception:
                context_part = user_prompt
        else:
            context_part = user_prompt

        return f"""# 📋 DEAL MEETING BRIEF

### 1. Deal Status & Stage
- **Current Stage**: Evaluation
- **Target Value / Budget**: ₹80,000
- **Primary Objective**: Automated invoice processing & cloud workflow integration

### 2. Key Requirements
- Processing capacity for ~10,000 monthly invoices automatically.
- **Critical Timeline Requirement**: Complete implementation required within **10 days** due to Q4 financial reporting.

### 3. Primary Unresolved Objections & Risks
- **SOC2 Security & Multi-tenant Compliance**: CSO David Vance requested detailed SOC2 security architecture whitepaper and data encryption documentation.
- **Previous Objection (Resolved)**: 10-day deployment pitch was accepted with high enthusiasm.

### 4. Commercial & Budget
- **Budget Discussed**: ₹80,000 (Approved by VP Finance Sarah Jenkins pending security clearance).

### 5. Competitive Landscape
- **Competitor X**: Offered ₹70,000, but lacks automated reconciliation and cloud security compliance.

### 6. Recommended Priorities & Action Plan
1. **Lead with Security Proof**: Present detailed SOC2 security architecture whitepaper to address David Vance's concerns.
2. **Reiterate Implementation Proof**: Reaffirm the accepted 10-day deployment schedule.
3. **Closing Plan**: Request final contract sign-off once security documentation is reviewed.

---
*Generated by Deal Intelligence Agent via Hindsight Memory Bank.*
*(Add GROQ_API_KEY in .env for custom dynamic Groq LLM generations)*
"""

    async def generate_completion(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        model: str = "llama-3.3-70b-versatile"
    ) -> str:
        if not self.client:
            return self._fallback_synthesize(system_prompt, user_prompt)

        try:
            response = await self.client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=temperature,
                max_tokens=2048
            )
            return response.choices[0].message.content or ""
        except Exception as e:
            try:
                response = await self.client.chat.completions.create(
                    model="llama3-70b-8192",
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    temperature=temperature,
                    max_tokens=2048
                )
                return response.choices[0].message.content or ""
            except Exception as e2:
                return self._fallback_synthesize(system_prompt, user_prompt)

llm_service = LLMService()
